// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dart.serviceclient.domain;

import com.dart.serviceclient.domain.EntrepriseAccount;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EntrepriseAccount_Roo_Configurable {
    
    declare @type: EntrepriseAccount: @Configurable;
    
}
