// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dart.serviceclient.domain;

import com.dart.serviceclient.domain.SearchEntreprise;
import java.io.Serializable;

privileged aspect SearchEntreprise_Roo_Serializable {
    
    declare parents: SearchEntreprise implements Serializable;
    
    private static final long SearchEntreprise.serialVersionUID = 1L;
    
}
